{% set name = "responsibleai" %}
{% set version = "0.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/responsibleai-{{ version }}.tar.gz
  sha256: 1aa46ef2385cb73e75eaafc9291a69df8ae448696db4e89b32f38f76e23c8870

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dice-ml >=0.9,<0.10
    - econml >=0.14.0
    - statsmodels <0.14.0
    - jsonschema
    - erroranalysis >=0.4.4
    - interpret-community >=0.29.0
    - lightgbm >=2.0.11
    - numpy >=1.17.2,<1.24.0
    - numba <=0.55.2
    - pandas >=0.25.1,<2.0.0
    - scikit-learn >=0.22.1,<1.1
    - scipy >=1.4.1
    - semver >=2.13.0,<2.14.dev0
    - ml-wrappers
    - networkx <=2.5
    - ipykernel <=6.8.0
    - markupsafe <=2.1.2
    - raiutils >=0.4.0

test:
  imports:
    - responsibleai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-toolbox
  summary: SDK API to explain models, generate counterfactual examples, analyze causal effects and analyze errors in Machine Learning models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
